# This file was generated by GoReleaser. DO NOT EDIT.
cask "fns-cli" do
  name "fns-cli"
  desc "Streamline your dev workflow from the terminal."
  homepage "https://github.com/afonsodemori/fns-cli"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fns-cli"

  on_macos do
    on_intel do
      url "https://github.com/afonsodemori/fns-cli/releases/download/v#{version}/fns-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "320cccac5a599acc590a393b07e82e348966daf86f9f500fdb4c1d4cd3f02176"
    end
    on_arm do
      url "https://github.com/afonsodemori/fns-cli/releases/download/v#{version}/fns-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "4511bbbc684f07dee107e048a3fc0072adb9dd7ed928e030244bbd40f3969575"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/afonsodemori/fns-cli/releases/download/v#{version}/fns-cli_#{version}_linux_amd64.tar.gz"
      sha256 "35b3d941bc5e9ca645cfa1d63d07a6e3937c5067e71ec55eb9f9c9b41a6216be"
    end
    on_arm do
      url "https://github.com/afonsodemori/fns-cli/releases/download/v#{version}/fns-cli_#{version}_linux_arm64.tar.gz"
      sha256 "d9143a1dd0cabc856f946d01b1a2d76e8debac412f77f578907061bf03d5f626"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fns-cli"]
    end
  end

  caveats do
    "To get started with fns-cli, run:"
    "  fns-cli --help"
  end

  # No zap stanza required
end
