# This file was generated by GoReleaser. DO NOT EDIT.
cask "fns-cli" do
  name "fns-cli"
  desc "Streamline your dev workflow from the terminal."
  homepage "https://github.com/afonsodemori/fns-cli"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fns-cli"

  on_macos do
    on_intel do
      url "https://github.com/afonsodemori/fns-cli/releases/download/v#{version}/fns-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "7daa769d58152c62e69a65e244c9ad874d76f43c963289d2e6758aeb284bdaf8"
    end
    on_arm do
      url "https://github.com/afonsodemori/fns-cli/releases/download/v#{version}/fns-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "36c3f024345adeb8314709e28e924e75509caf75e816b186d4cfae21c3961d54"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/afonsodemori/fns-cli/releases/download/v#{version}/fns-cli_#{version}_linux_amd64.tar.gz"
      sha256 "832e3dfb0547ffe3ae3c793d382e5a532b3686cd5f0726d7f31b9b6bb9d660de"
    end
    on_arm do
      url "https://github.com/afonsodemori/fns-cli/releases/download/v#{version}/fns-cli_#{version}_linux_arm64.tar.gz"
      sha256 "78391a4c78f7bbb6a4d299e5440424336f4c15efe92f4c82add9d9684cf8adbd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fns-cli"]
    end
  end

  caveats do
    "To get started with fns-cli, run:"
    "  fns-cli --help"
  end

  # No zap stanza required
end
