# This file was generated by GoReleaser. DO NOT EDIT.
cask "fns-cli" do
  name "fns-cli"
  desc "Streamline your dev workflow from the terminal."
  homepage "https://github.com/afonsodemori/fns-cli"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fns-cli"

  on_macos do
    on_intel do
      url "https://github.com/afonsodemori/fns-cli/releases/download/v#{version}/fns-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "8d43d6f537d938cd5c673fa984481588c44f18ee04f82f6d05ad04cbead67fc9"
    end
    on_arm do
      url "https://github.com/afonsodemori/fns-cli/releases/download/v#{version}/fns-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "ad12b7613a158f24e7de9443ed45da85d9b33c20c0bf58555c9b6ddbf9ee3e2f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/afonsodemori/fns-cli/releases/download/v#{version}/fns-cli_#{version}_linux_amd64.tar.gz"
      sha256 "6f5f1204d530aa957b3845ceb6d7c2d3dffadf555f18aa1a70e260161db780b5"
    end
    on_arm do
      url "https://github.com/afonsodemori/fns-cli/releases/download/v#{version}/fns-cli_#{version}_linux_arm64.tar.gz"
      sha256 "72449c0008f5f5f3b83cda9247efdb93c7497af464a412e0669f2d1b7229b437"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fns-cli"]
    end
  end

  caveats do
    "To get started with fns-cli, run:"
    "  fns-cli --help"
  end

  # No zap stanza required
end
